server:
  port: 8081
  servlet:
    context-path: /custom-path

spring:
  application:
    name: cuenta
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dbtechnicaltest
    username: postgres
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

application:
  endpoints:
    url:
      get_client: http://localhost:8080/clientes/{clientId}

