server:
  port: 8080
  servlet:
    context-path: /custom-path

spring:
  application:
    name: cliente
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/dbtechnicaltest
    username: postgres
    password: 123456
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

